DWAPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
# The velocity when robot is moving in a straight line
  max_trans_vel:  0.25
  min_trans_vel:  0.1
  max_rot_vel: 5.0
  min_rot_vel: 0.4
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.0
# Goal Tolerance Parametes
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 6
  vy_samples: 0
  vth_samples: 20
  controller_frequency: 20.0
# Trajectory Scoring Parameters
  path_distance_bias: 64.0
  goal_distance_bias: 24.0
  occdist_scale: 0.3
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true